use_gpu: True
use_gram: True
device: 0
eval_device: 0
early_stop:
  patience: 0
federate:
  method: fedavg
  freeze_A: True
  mode: standalone
  client_num: 3
  total_round_num: 3
  save_to: "glue_wallclock_fa_lora.ckpt"
  save_freq: 0
  share_local_model: True
  online_aggr: False
personalization:
  local_param: ['classifier']
data:
  root: data/
  type: "sst2@glue"
  matched: True
  splitter: "iid"
  glue:
    train_size: 384
    val_size: 96
    sample_seed: 42
llm:
  tok_len: 128
  adapter:
    use: True
    args: [{ 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 }]
dataloader:
  batch_size: 16
  num_workers: 0
  pin_memory: False
model:
  type: "FacebookAI/roberta-large@huggingface_llm"
train:
  local_update_steps: 4
  batch_or_epoch: batch
  optimizer:
    lr: 0.02
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: gluetrainer
eval:
  freq: 1000000
  metrics: ["accuracy"]
  count_flops: False
  best_res_update_round_wise_key: "val_accuracy"
  split: ["val"]
wandb:
  use: False
grad:
  grad_clip: 1.0
